### ISSUE TITLE
Fails to build on zeek (master)

### ISSUE THREAD

**Issue by blacktop** [J-Gras/zeek-af_packet-plugin#11]
```bash
/tmp/zeek/aux/bro-af_packet-plugin/src/AF_Packet.cc:2:24: fatal error: bro-config.h: No such file or directory
 #include "bro-config.h"
                        ^
compilation terminated.
make[3]: Leaving directory '/tmp/zeek/aux/bro-af_packet-plugin/build'
make[2]: Leaving directory '/tmp/zeek/aux/bro-af_packet-plugin/build'
make[3]: *** [CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/build.make:95: CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/src/AF_Packet.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:72: CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/all] Error 2
make[1]: *** [Makefile:130: all] Error 2
make[1]: Leaving directory '/tmp/zeek/aux/bro-af_packet-plugin/build'
make: *** [Makefile:13: build-it] Error 2
```

I know they are in the process of renaming bro to zeek in a lot of the code now.  Maybe it's `zeek-config.h` now?

**Comment by J-Gras** [comment]
Thanks for reporting! As the renaming is still in progress (see https://github.com/zeek/zeek/projects/2), I haven't had a look so far. I am planning to do a cleanup and renaming once there is a zeek 3 beta.

**Comment by blacktop** [comment]
I believe that day has come 😀

**Comment by J-Gras** [comment]
It should work just fine but I will investigate on how to provide a zeekified version of the plugin without breaking compatibility.

**Comment by mmguero** [comment]
I can confirm, working the same way for me. Constant streaming of this message:

```
Warning: ZeekControl plugin uses legacy BroControl API. Use
'import ZeekControl.plugin' instead of 'import BroControl.plugin'
```

and this one on startup:

```
Warning: Plugin 'af_packet' uses deprecated method 'broctl_config'; use 'zeekctl_config' instead
```

But other than that it does seem to be running okay at this point. (Debian 10)

**Comment by JustinAzoff** [comment]
One way to get rid of  warnings is to do this  in the  plugin:

```
try:
    import ZeekControl.plugin as PluginBase
    from ZeekControl import cmdresult
except ImportError:
    import BroControl.plugin as PluginBase
    from BroControl import cmdresult
```

or such, then inherit from  PluginBase.   I'm not sure how  much I like that method  though.. it might be  better  to just mark old  plugins as for bro >= 2.6 and < 3,  and release new  plugins as >= 3.0.0 but I'm not sure if zkg can handle that.

**Comment by kraigu** [comment]
I don't know if this should be a separate issue, but the configure script breaks with 3.1 alpha - I think bro-config doesn't give it any of the output it's expecting and configure exits. Replacing bro-config with zeek-config results in a working Makefile, but I'm still seeing errors compiling (possibly due to PEBCAK here, I only just started poking at this):

```
/usr/local/src/bro-af_packet-plugin/src/AF_Packet.h:67:21: error: field ‘current_hdr’ has incomplete type ‘pcap_pkthdr’
  struct pcap_pkthdr current_hdr;
                     ^~~~~~~~~~~
In file included from /usr/local/src/bro-af_packet-plugin/src/AF_Packet.h:22:0,
                 from /usr/local/src/bro-af_packet-plugin/src/Plugin.cc:3:
/srv/zeek/include/zeek/iosource/PktSrc.h:12:8: note: forward declaration of ‘struct pcap_pkthdr’
 struct pcap_pkthdr;
        ^~~~~~~~~~~
/usr/local/src/bro-af_packet-plugin/src/Plugin.cc: In member function ‘virtual plugin::Configuration plugin::Bro_AF_Packet::Plugin::Configure()’:
/usr/local/src/bro-af_packet-plugin/src/Plugin.cc:11:19: error: expected type-specifier before ‘::’ token
  AddComponent(new ::iosource::PktSrcComponent("AF_PacketReader", "af_packet", ::iosource::PktSrcComponent::LIVE, ::iosource::pktsrc::AF_PacketSource::InstantiateAF_Packet));
                   ^~
```

**Comment by JustinAzoff** [comment]
@kraigu https://github.com/J-Gras/bro-af_packet-plugin/pull/15 was merged right after your comment which should fix things.

https://github.com/J-Gras/bro-af_packet-plugin/pull/15/commits/8d7656257dcbcf7bf6bd74de19a04bd8cf768805 specifically fixes the pcap_pkthdr issue

**Comment by J-Gras** [comment]
Right, master should already work with zeek 3.1. I am also about to rename the plugin itsef. I just need to verify that switching works as intended and then I will also add a new release tag.

**Comment by J-Gras** [comment]
Renaming is completed.
